source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

def shared_pods
  pod 'AFNetworking', '~> 3.0'
end

target 'TubeNearLondon' do

  # Pods for TubeNearLondon
  shared_pods

  target 'TubeNearLondonTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
  end

end
